# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 151))
        self.groupBox.setObjectName("groupBox")
        self.com_list = QtWidgets.QComboBox(self.groupBox)
        self.com_list.setGeometry(QtCore.QRect(12, 32, 86, 25))
        self.com_list.setObjectName("com_list")
        self.buttonOk = QtWidgets.QPushButton(self.groupBox)
        self.buttonOk.setGeometry(QtCore.QRect(104, 32, 80, 25))
        self.buttonOk.setObjectName("buttonOk")
        self.buttonCancel = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancel.setGeometry(QtCore.QRect(190, 32, 80, 25))
        self.buttonCancel.setObjectName("buttonCancel")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(16, 68, 111, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_delay = QtWidgets.QLabel(self.widget)
        self.label_delay.setObjectName("label_delay")
        self.verticalLayout.addWidget(self.label_delay)
        self.label_status = QtWidgets.QLabel(self.widget)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(149, 68, 121, 61))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd = QtWidgets.QLCDNumber(self.widget1)
        self.lcd.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd.setObjectName("lcd")
        self.verticalLayout_2.addWidget(self.lcd)
        self.label_color = QtWidgets.QLabel(self.widget1)
        self.label_color.setFrameShape(QtWidgets.QFrame.Box)
        self.label_color.setText("")
        self.label_color.setObjectName("label_color")
        self.verticalLayout_2.addWidget(self.label_color)
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(10, 190, 641, 381))
        self.graph.setObjectName("graph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Макет - 1"))
        self.groupBox.setTitle(_translate("MainWindow", "Приемник"))
        self.buttonOk.setText(_translate("MainWindow", "Ok"))
        self.buttonCancel.setText(_translate("MainWindow", "Cancel"))
        self.label_delay.setText(_translate("MainWindow", "Уровень"))
        self.label_status.setText(_translate("MainWindow", "Статус"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
